version: 0.2

env:
  variables:
    TF_VERSION: "1.5.5"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install packer
      - python3 -m pip -V
      - python3 -m pip install --user ansible
  build:
    commands:
