version: 0.2

env:
  variables:
    TF_VERSION: "1.5.5"


phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install packer
      - python3 -m pip -V
      - python3 -m pip install --user ansible
      - packer version
      - export PATH=/root/.local/bin:$PATH
      - ansible --version
  build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SRC_DIR_playbook
      - ls -ltr $CODEBUILD_SRC_DIR_playbook
      - cd $CODEBUILD_SRC_DIR/packerfile
      - packer init w2022.pkr.hcl
      - packer build -var "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}" -var "VPC_ID=${VPC_ID}" -var "SUBNET_ID=${SUBNET_ID}" -var "PLAYBOOK=${CODEBUILD_SRC_DIR_playbook}/Windows-2022-CIS/site.yml" w2022.pkr.hcl 
artifacts:
  files:
    - '**/*'
  name: $IMAGE_REPO_NAME
