version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install packer
      - python3 -m pip -V
      - python3 -m pip install --user ansible
      - pip install pywinrm
      - packer version
      - export PATH=/root/.local/bin:$PATH
      - ansible --version
  build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR/scripts
      - cd $CODEBUILD_SRC_DIR/packerfile
      - cat ${PROJECT_NAME}.pkr.hcl
      - packer init ${PROJECT_NAME}.pkr.hcl
      - packer build -var "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}" -var "VPC_ID=${VPC_ID}" -var "SUBNET_ID=${SUBNET_ID}" -var "PLAYBOOK=${CODEBUILD_SRC_DIR_playbook}/site.yml" -var "BUILDNUM=${CODEBUILD_BUILD_NUMBER}" -var "AMI=${AMI_NAME}" -var "INSTANCE_PROFILE=${INSTANCE_PROFILE}" ${PROJECT_NAME}.pkr.hcl 
