version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install packer jq
      - python3 -m pip -V
      - python3 -m pip install --user ansible
      - pip install pywinrm
      - packer version
      - export PATH=/root/.local/bin:$PATH
      - ansible --version
  build:
    commands:
      - ls -l $CODEBUILD_SRC_DIR/scripts
      - cd $CODEBUILD_SRC_DIR/packerfile
      - packer init ${PROJECT_NAME}.pkr.hcl
      - packer build -var "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}" -var "VPC_ID=${VPC_ID}" -var "SUBNET_ID=${SUBNET_ID}" -var "PLAYBOOK=${CODEBUILD_SRC_DIR_playbook}/site.yml" -var "BUILDNUM=${CODEBUILD_BUILD_NUMBER}" -var "AMI=${AMI_NAME}" -var "INSTANCE_PROFILE=${INSTANCE_PROFILE}" ${PROJECT_NAME}.pkr.hcl 
