version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
    commands:
      - yum install -y yum-utils libxcrypt-compat
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y packer
      - yum install -y https://afutest101.s3.us-east-1.amazonaws.com/inspec-4.3.2-1.el7.x86_64.rpm
      - inspec version
      - packer version
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/packerfile
      - packer init inspec.${PROJECT_NAME}.pkr.hcl
      - |
        packer build \
          -var "SECURITY_GROUP_ID=${SECURITY_GROUP_ID}" \
          -var "VPC_ID=${VPC_ID}" \
          -var "SUBNET_ID=${SUBNET_ID}" \
          -var "BUILDNUM=${CODEBUILD_BUILD_NUMBER}" \
          -var "AMI_ID=${AMI_ID}" \
          -var "INSTANCE_PROFILE=${INSTANCE_PROFILE}" \
          -var "PROJECT=${PROJECT_NAME}" \
          inspec.${PROJECT_NAME}.pkr.hcl || true
      - mv results.xml $CODEBUILD_SRC_DIR/
reports:
  inspec-reports:
    files:
      - results.xml
artifacts:
  files:
    - results.xml